services:
  db:
    container_name: "eduportal-fastapi-postgres"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER -d POSTGRES_PASSWORD"]
      interval: 1m
      timeout: 30s
      retries: 5
    networks:
      - custom

networks:
  custom:
    driver: bridge
