"""Added new field to 'users' - 'roles'

Revision ID: 842d3ea30980
Revises: 23d08caf6e83
Create Date: 2025-05-07 16:49:47.899056

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "842d3ea30980"
down_revision: Union[str, None] = "23d08caf6e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("roles", sa.ARRAY(sa.String())), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
